server {
    listen 443 ssl;

    server_name
        flowcrypt.test
        *.flowcrypt.test;

    ssl_certificate     /etc/nginx/certs/server_combined.pem;
    ssl_certificate_key /etc/nginx/certs/server_combined.pem;

    location / {
        default_type text/plain;
        return 200 "hello from docker https mock server\n";
    }
}